version: 1

formatters:
  testFormatter:
    format: '< %(asctime)s [%(levelname)s] > %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file_MnvBatchExecuteTheSmsQuery:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: testFormatter
    filename: MnvBatchExecuteTheSmsQuery.log
    maxBytes: 2000000
    backupCount: 1

loggers:
  MnvBatchExecuteTheSmsQuery:
    level: INFO
    handlers: [file_MnvBatchExecuteTheSmsQuery]
    propagate: no

root:
  level: INFO
  handlers: []
